### ISSUE TITLE
\n at the end of hashed and non hashed password

### ISSUE THREAD

**Issue by Polichronucci** [debops/ansible-grub#12]
In line 73 and 105 there is an "\n" added. This gets inserted in the "/etc/grub.d/01_users" file and so in the "/boot/grub/grub.cfg". This breaks functionality and gets grub login prompt unusable. 
By removing the "\n" on both lines fixes this issue.
This was tested only on a Debian Jessie machine.

**Comment by drybjed** [comment]
@Polichronucci What Ansible version do you use? IIRC, 2.0+ made changes to how `\n` is handled in different places, that might cause the issue here.

@ypid, have you seen anything similar?

**Comment by Polichronucci** [comment]
Yes I'm using 2.1.0.0.
Maybe a version check can handle this.

**Comment by ypid** [comment]
Not sure. I have not used this feature for some time.

**Comment by ypid** [comment]
I now found the time to check/use this again. @Polichronucci Thanks very much for reporting and for providing the fix! PR opened #16 which fixes it.
