### ISSUE TITLE
"Generate salted hash from user password" task requires LANG=C

### ISSUE THREAD

**Issue by thoemy** [debops/ansible-grub#18]
For systems that are set to a different language than English, `grub-mkpasswd-pbkdf2` might return localized messages. This breaks the regular expression that extracts the hashed password.

Adding an environment section to the task fixes the problem.

```yaml
  environment:
    LANG: C
```

The RE currently is `s/^(:?Your PBKDF2|PBKDF2 hash of your password) is //ms`. In German the following is returned from `grub-mkpasswd-pbkdf2`.
```
Passwort eingeben:
Passwort erneut eingeben:
PBKDF2-Prüfsumme Ihres Passworts ist grub.pbkdf2.sha512.2.5650688D7E4B317D00D78...
```

**Comment by drybjed** [comment]
Thanks for the issue report. If you want to help fixing it, you could create a pull request in the [debops/debops](https://github.com/debops/debops) repository.

**Comment by drybjed** [comment]
This issue should be fixed by https://github.com/debops/debops/pull/466, in the DebOps monorepo. Closing.
