### ISSUE TITLE
Use of grub_kernel_options for GRUB_CMDLINE_LINUX should be document

### ISSUE THREAD

**Issue by berendt** [debops/ansible-grub#8]
At the moment the documentation does not mention that `grub_kernel_options` will be used for `GRUB_CMDLINE_LINUX`. Would be nice to note this in the documentation of `grub_kernel_options`.

**Comment by ypid** [comment]
@berendt Thanks for the hint. Would you like to document it? You can find the sources for the docs here: https://github.com/debops/ansible-grub/tree/master/docs

**Comment by drybjed** [comment]
Actually, according to [this AskUbuntu entry](https://askubuntu.com/questions/575651/), `GRUB_CMDLINE_LINUX` and `GRUB_CMDLINE_LINUX_DEFAULT` have specific purpose:

- `GRUB_CMDLINE_LINUX_DEFAULT` is used only during normal kernel boot
- `GRUB_CMDLINE_LINUX` is used during normal and recovery kernel boot

Therefore I think that the current role misues these variables, and should be changed to align with the intended use. The normal boot options shouldn't affect the recovery boot options, which is the case currently.

**Comment by drybjed** [comment]
This issue should be fixed by https://github.com/debops/debops/pull/466, in the DebOps monorepo. Closing.
